version: '3.6'
services:
  redis-rdb:
    build:
      context: ./redis-rdb
    container_name: redis-rdb
    ports:
      - '6381:6379'
    volumes:
      - ./redis-rdb/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redisdb-rdb:/data/db
    networks:
      - queues

  redis-aof:
    build:
      context: ./redis-aof
    container_name: redis-aof
    ports:
      - '6382:6379'
    volumes:
      - ./redis-aof/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redisdb-aof:/data/db
    networks:
      - queues

  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - '11300:11300'
    volumes:
      - ./data/beanstalkd_data:/var/lib/beanstald
    networks:
      - queues

networks:
  queues:
    driver: bridge
